version: '3.9'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
      - dev-static-data:/vol/web/
    ports:
      - "8001:8001"
    entrypoint: ["/entrypoint.sh"]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  dev-static-data:
