---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-24.04
    steps:
      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: checkout 
        uses: actions/checkout@v4
      - name: Test
        run : docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run : docker compose run --rm app sh -c "flake8 ."  
        
        
        
    
  

